# Generated by Django 4.0.6 on 2022-07-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Coimbatore', 'Coimbatore'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDBModel',
            fields=[
                ('emp_no', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('Coimbatore', 'Coimbatore'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi')], max_length=30)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_fullname', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('blood_group', models.CharField(choices=[('A-positive (A+)', 'A-positive (A+)'), ('A-negative (A-)', 'A-negative (A-)'), ('B-positive (B+)', 'B-positive (B+)'), ('B-negative (B-)', 'B-negative (B-)'), ('AB-positive (AB+)', 'AB-positive (AB+)'), ('AB-negative (AB-)', 'AB-negative (AB-)'), ('O-positive (O+)', 'O-positive (O+)'), ('O-negative (O-)', 'O-negative (O-)')], max_length=20)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('contact_number', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='media/')),
            ],
            options={
                'db_table': 'EmployeeDBModel',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.SmallIntegerField()),
                ('branch', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='api.branchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_fullname', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('blood_group', models.CharField(choices=[('A-positive (A+)', 'A-positive (A+)'), ('A-negative (A-)', 'A-negative (A-)'), ('B-positive (B+)', 'B-positive (B+)'), ('B-negative (B-)', 'B-negative (B-)'), ('AB-positive (AB+)', 'AB-positive (AB+)'), ('AB-negative (AB-)', 'AB-negative (AB-)'), ('O-positive (O+)', 'O-positive (O+)'), ('O-negative (O-)', 'O-negative (O-)')], max_length=20)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('contact_number', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='media/')),
                ('emp_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.employeemodel')),
            ],
        ),
    ]
