# Generated by Django 4.0.6 on 2022-07-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeemodel1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeModel1',
        ),
    ]
